name: Test Action
on: [pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run action
        id: run_action
        uses: ./
        with:
          email: ${{ secrets.CONFLUENCE_EMAIL }}
          api_token: ${{ secrets.CONFLUENCE_API_TOKEN }}
          host: solidstatenetworks.jira.com
          space_key: ${{ secrets.CONFLUENCE_SPACE_KEY }}
          page_id: ${{ secrets.CONFLUENCE_PAGE_ID }}
          title: Test Change Log
          tag: 1.1.0
          repository: snxd/jira-version-action
